version: '3'
services:
  bsc-node:
    container_name: bsc
    image:  brokedtv/bsc:v1.1.16
    restart: always
    command: --txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000
    volumes:
      - ./data/bsc:/root
    ports:
      - "8545:8545"
      - "30311:30311"
      - "30311:30311/udp"
      - "8546:8546"
      - "6060:6060"

